---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      customize:
        memory: 2048
        cpuexecutioncap: 50

suites:
  - name: server
    run_list:
      - recipe[chef-server::default]
    attributes:
